FROM node:alpine
WORKDIR '/app'
COPY ./package.json ./
RUN npm install
COPY ./ ./

# NOTE: run dev is to execute the "dev" script in package.json which launches nodemon,
# which monitors for code changes
CMD ["npm", "run", "dev"]